Entity/Page.php
<?php

namespace Soloist\Bundle\BlockBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use FrequenceWeb\Bundle\DashboardBundle\Crud\CrudableInterface;

class Page implements CrudableInterface
{
    /**
     * @var integer
     */
    protected $id;

    /**
     * The template used to display the page
     *
     * @var string
     */
    protected $template;

    /**
     * The page name (used for identification)
     *
     * @var string
     */
    protected $name;

    /**
     * The page slug
     *
     * @var string
     */
    protected $slug;

    /**
     * @var ArrayCollection
     */
    protected $blocks;

    /**
     * @var \DateTime
     */
    protected $createdAt;

    /**
     * @var \DateTime
     */
    protected $updatedAt;

    public function __construct()
    {
        $this->blocks = new ArrayCollection;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $template
     */
    public function setTemplate($template)
    {
        $this->template = $template;
    }

    /**
     * @return string
     */
    public function getTemplate()
    {
        return $this->template;
    }

    /**
     * @param string $slug
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    }

    /**
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @return array
     */
    public function getRouteParams()
    {
        return array(
            'id' => $this->id
        );
    }

    /**
     * @param  Block $block
     *
     * @return Page
     */
    public function addBlock(Block $block)
    {
        $this->blocks[] = $block;
        $block->setPage($this);

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getBlocks()
    {
        return $this->blocks;
    }
}

Controller/AdminBlockController.php
<?php

namespace Soloist\Bundle\BlockBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Soloist\Bundle\BlockBundle\Entity\Block;
use Soloist\Bundle\BlockBundle\Entity\Page;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class AdminBlockController extends Controller
{
    /**
     * @Template
     *
     * @param  Page  $page
     *
     * @return array
     */
    public function indexAction(Page $page)
    {
        $this->get('fw_breadcrumbs')
            ->add('Tableau de bord', array('route' => 'fw_dashboard_index'))
            ->add('Gestion des pages-blocs', array('route' => 'soloist_admin_block_page_index'))
            ->add('Page "'.$page->getName().'"', array(
                'route'        => 'soloist_admin_block_page_edit',
                'route_params' => $page->getRouteParams()
            ))
            ->add('Gérer les blocs')
        ;

        return array('page' => $page);
    }

    /**
     * @Template
     *
     * @param  Page  $page
     *
     * @return array
     */
    public function getBlocksAction(Page $page)
    {
        return array('page' => $page, 'manager' => $this->get('soloist.block.manager'));
    }

    /**
     * @Template
     *
     * @return array
     */
    public function listBlockTypesAction()
    {
        return array('blocks' => $this->get('soloist.block.manager')->getBlockTypes());
    }

    /**
     * @param  Page     $page
     * @param  Request  $request
     *
     * @return Response
     */
    public function addAction(Page $page, Request $request)
    {
        $em    = $this->getDoctrine()->getManager();
        $block = Block::createFromData($page, $request->request->all());
        $em->persist($block);
        $em->flush();

        return new Response(json_encode(array(
            'blocks' => $this->container->get('templating.helper.actions')->render(
                'SoloistBlockBundle:AdminBlock:getBlocks',
                array('page' => $page)
            ),
            'library' =>$this->container->get('templating.helper.actions')->render(
                'SoloistBlockBundle:AdminBlock:listBlockTypes'
            )
        )));
    }

    /**
     * @Template("SoloistBlockBundle:AdminBlock:getBlocks.html.twig")
     *
     * @param  Block         $block
     *
     * @return array<string>
     */
    public function deleteAction(Block $block)
    {
        $page = $block->getPage();
        $em   = $this->getDoctrine()->getManager();
        $em->remove($block);
        $em->flush();

        return array('page' => $page, 'manager' => $this->get('soloist.block.manager'));
    }

    /**
     * @param  Block    $block
     * @param  Request  $request
     *
     * @return Response
     */
    public function configureAction(Block $block, Request $request)
    {
        $manager   = $this->get('soloist.block.manager');
        $blockType = $manager->getBlockType($block->getType());
        $form = $this->get('form.factory')->create($blockType['form'], $block->getSettings());

        if ('POST' === $request->getMethod()) {
            $form->bindRequest($request);
            if ($form->isValid()) {
                $block->setSettings($form->getData());
                $this->getDoctrine()->getManager()->flush();
            }
        }

        return $this->render(
            isset($blockType['form_template']) ? $blockType['form_template'] : 'SoloistBlockBundle:AdminBlock:configure.html.twig',
            array('block' => $block, 'block_type' => $blockType, 'form' => $form->createView())
        );
    }

    /**
     * @param  Block    $block
     * @param  Request  $request
     *
     * @return Response
     */
    public function sortAction(Block $block, Request $request)
    {
        $position = $request->query->get('position', 0);
        $block->setPosition($position);
        $this->getDoctrine()->getManager()->flush();

        return new Response(json_encode(array('success' => true)));
    }
}

Resources/views/AdminBlock/configure.html.twig
<div class="modal-header">
    <h3>Configuration du bloc "{{ block_type.name }}"</h3>
</div>
<form method="POST" action="{{ path('soloist_admin_block_block_configure', block.routeParams) }}">
    <div class="modal-body">
        <fieldset>
            {% block form %}
                {{ form_rest(form) }}
            {% endblock %}
        </fieldset>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Valider</button>
        <a id="configure-close" class="btn">Annuler</a>
    </div>
</form>

Resources/views/AdminBlock/configureAccordionBlock.html.twig
{% extends 'SoloistBlockBundle:AdminBlock:configure.html.twig' %}

Resources/views/AdminBlock/getBlocks.html.twig
{% for block in page.blocks %}

    <div class="thumbnail" data-sort-uri="{{ path('soloist_admin_block_block_sort', block.routeParams) }}">
        <div class="caption">
            <h4>{{ manager.getBlockType(block.type).name }}</h4>
            <div class="actions">
                <a href="{{ path('soloist_admin_block_block_delete', block.routeParams) }}"
                   class="btn btn-mini btn-danger delete pull-right">
                    <i class="icon-trash icon-white"></i>
                    Supprimer
                </a>
                <a href="{{ path('soloist_admin_block_block_configure', block.routeParams) }}"
                   class="btn btn-mini configure pull-right">
                    <i class="icon-edit"></i>
                    Configurer
                </a>
            </div>
            <hr />
        </div>
    </div>

{% endfor %}

Resources/views/AdminBlock/index.html.twig
{% extends 'FrequenceWebDashboardBundle::admin.html.twig' %}

{% block body %}
    <h1>Gestion des pages-blocs</h1>

    <div class="row-fluid" id="soloist-block-blocks">

        <div class="span5">
            <h2>Blocs</h2>
            <div class="well" id="block-container">
                {% render 'SoloistBlockBundle:AdminBlock:getBlocks' with { page: page } %}
            </div>
        </div>

        <div class="span7">
            <h2>Bibliothèque</h2>
            <div id="block-library">
                {% render 'SoloistBlockBundle:AdminBlock:listBlockTypes' %}
            </div>
        </div>

    </div>

{% endblock %}

{% block javascripts %}
{%- javascripts '@SoloistBlockBundle/Resources/coffee/*.coffee' filter="coffee, ?yui_js" %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
{%- endjavascripts %}
<script type="text/javascript">
    new window.soloist.BlockManager({
        'addUri':  '{{ path('soloist_admin_block_block_add', page.routeParams) }}'
    });
</script>
{% endblock %}

Resources/views/AdminBlock/listBlockTypes.html.twig
{% set i = 0 %}

{% macro close_row(i) %}
    {% if i != 0 and i % 3 == 0 %}
        </div>
        <div class="row-fluid">
    {% endif %}
{% endmacro %}

<div class="row-fluid">
    {% for type, params in blocks%}
        {{ _self.close_row(i) }}{% set i = i + 1 %}
        <div class="span4">
            <div class="draggable-block thumbnail">
                <div class="caption">
                    <h4>{{ params.name }}</h4>
                    <form>
                        <input type="hidden" name="type"   value="{{ type }}" />
                        <input type="hidden" name="action" value="{{ params.action }}" />
                        {% for setting, value in params.settings %}
                            <input type="hidden" name="settings[{{ setting }}]" value="{{ value }}" />
                        {% endfor %}
                    </form>
                </div>
            </div>
        </div>
    {% endfor %}
</div>